import PodAffinityAntiAffinity from "../pages/note/PodAffinityAntiAffinity.jsx";

export const noteRoutes = [
    { path: "/whatIsCloud", label: "클라우드란 무엇인가?" },
    { path: "/createEC2", label: "EC2 인스턴스 생성" },
    { path: "/sshConection", label: "SSH 접속" },
    { path: "/createRDS", label: "RDS 인스턴스 생성" },
    { path: "/rdsConection", label: "RDS 인스턴스 연결" },
    { path: "/whatIsDocker", label: "도커란 무엇인가?" },
    { path: "/whatIsKubernetes", label: "쿠버네티스란 무엇인가?" },
    { path: "/podAndService", label: "쿠버네티스의 파드와 서비스" },
    { path: "/replicaSetAndDeployment", label: <>ReplicaSet과<br />Deployment란?</> },
    { path: "/kubernetesSummary", label: <>쿠버네티스 핵심 리소스<br />한눈에 보기</> },
    { path: "/whatIsMinikube", label: "Minikube란 무엇인가?" },
    { path: "/kopsOnAWS", label: <>Kops로 AWS에 쿠버네티스<br />클러스터 구성하기</> },
    { path: "/kopsSetupGuide", label: <>Kops 클러스터 구성<br />AWS & DNS 설정 가이드</> },
    { path: "/kubernetesAdvancedDemo", label: <>쿠버네티스 고급 명령어 및<br />클러스터 내 통신</> },
    { path: "/replicationControllerDemo", label: <>ReplicationController<br />수평 확장 데모</> },
    { path: "/healthCheck", label: "헬스 체크" },
    { path: "/livenessReadiness", label: <>Liveness와<br />Readiness Probe</> },
    { path: "/podStatus", label: "파드(Pod)의 상태 이해하기" },
    { path: "/podLifecycle", label: "파드 수명 주기" },
    { path: "/secret", label: "쿠버네티스 시크릿" },
    { path: "/wordPressDemo", label: "워드프레스 데모" },
    { path: "/kubernetesDashboard", label: "쿠버네티스 웹 UI 대시보드" },
    { path: "/kubernetesDNSDiscovery", label: <>Kubernetes DNS를 이용한<br/>서비스 탐색</>},
    { path: "/serviceDiscoveryDemo", label: <>서비스 탐색 (DNS 기반) 데모</>},
    { path: "/kubernetesConfigMap", label: <>Kubernetes ConfigMap<br/>이해 및 활용</>},
    { path: "/configMapNginxProxy", label: <>ConfigMap + NGINX <br/>리버스 프록시 데모</>},
    { path: "/kubernetesIngress", label: <>인그레스와 인그레스<br/>컨트롤러</>},
    { path: "/externalDNSIngress", label: <>외부 DNS + 인그레스 개요</>},
    { path: "/kubernetesVolume", label: <>쿠버네티스 볼륨 <br/>& 퍼시스턴트 볼륨 요약</>},
    { path: "/volumeProvisioning", label: <>볼륨 프로비저닝과 <br/> 워드프레스 데모</>},
    { path: "/podPreset", label: <>PodPreset란?<br/>(파드 자동 설정 주입)</>},
    { path: "/statefulSetCassandra", label: <>StatefulSet로 Cassandra <br/>클러스터 배포 데모)</>},
    { path: "/hpa", label: <>오토스케일링</>},
    { path: "/affinityAntiAffinity", label: <>어피니티 & 안티 어피니티</>},
    { path: "/podAffinityAntiAffinity", label: <>파드 간 어피니티 & <br/>안티어피니티</>},


];
