export const noteRoutes = [
    { path: "/whatIsDocker", label: "도커란 무엇인가?" },
    { path: "/whatIsKubernetes", label: "쿠버네티스란 무엇인가?" },
    { path: "/podAndService", label: "쿠버네티스의 파드와 서비스" },
    { path: "/replicaSetAndDeployment", label: "ReplicaSet과 Deployment란?" },
    { path: "/kubernetesSummary", label: "쿠버네티스 핵심 리소스 한눈에 보기" },
    { path: "/whatIsMinikube", label: "Minikube란 무엇인가?" },
    { path: "/kopsOnAWS", label: "Kops로 AWS에 쿠버네티스 클러스터 구성하기" },
    { path: "/kopsSetupGuide", label: "Kops 클러스터 구성 AWS & DNS 설정 가이드" },
    { path: "/kubernetesAdvancedDemo", label: "쿠버네티스 고급 명령어 및 클러스터 내 통신" },
    { path: "/replicationControllerDemo", label: "ReplicationController 수평 확장 데모" },
    { path: "/healthCheck", label: "헬스 체크" },
    { path: "/livenessReadiness", label: "Liveness와 Readiness Probe" },
    { path: "/podStatus", label: "파드(Pod)의 상태 이해하기" },
    { path: "/podLifecycle", label: "파드 수명 주기" },
    { path: "/secret", label: "쿠버네티스 시크릿" },
    { path: "/wordPressDemo", label: "워드프레스 데모" },
    { path: "/kubernetesDashboard", label: "쿠버네티스 웹 UI 대시보드" },
    { path: "/kubernetesDNSDiscovery", label: "Kubernetes DNS를 이용한 서비스 탐색" },
    { path: "/serviceDiscoveryDemo", label: "서비스 탐색 (DNS 기반) 데모" },
    { path: "/kubernetesConfigMap", label: "Kubernetes ConfigMap 이해 및 활용" },
    { path: "/configMapNginxProxy", label: "ConfigMap + NGINX 리버스 프록시 데모" },
    { path: "/kubernetesIngress", label: "인그레스와 인그레스 컨트롤러" },
    { path: "/externalDNSIngress", label: "외부 DNS + 인그레스 개요" },
    { path: "/kubernetesVolume", label: "쿠버네티스 볼륨 & 퍼시스턴트 볼륨 요약" },
    { path: "/volumeProvisioning", label: "볼륨 프로비저닝과 워드프레스 데모" },
    { path: "/podPreset", label: "PodPreset란? (파드 자동 설정 주입)" },
    { path: "/statefulSetCassandra", label: "StatefulSet로 Cassandra 클러스터 배포 데모)" },
    { path: "/hpa", label: "오토스케일링" },
    { path: "/affinityAntiAffinity", label: "어피니티 & 안티 어피니티" },
    { path: "/podAffinityAntiAffinity", label: "파드 간 어피니티 & 안티어피니티" },
    { path: "/taintsAndTolerations", label: "테인트(Taint) & 톨러레이션(Toleration)" },
];